### ISSUE TITLE
not downloading for nexus mods

### ISSUE THREAD

**Issue by saltyred** [toebeann/subnautica-support#9]
i am trying to import mods for subnautica and it wont let me for some reason might be a bug on my end might not hard to tell

**Comment by toebeann** [comment]
This isn't really the place for this query, however if you're still having problems let me know. I just tested by updating Vortex, uninstalling the extension and then when attempting to manage Subnautica with Vortex it prompted me to install the community extension and then restarted itself with the extension installed, so it seems the extension is working fine on my end. If it is not for you, then I will need more details.

Additionally, you can also follow the instructions on how to manually install the extension if automated installation isn't working.

**Comment by toebeann** [comment]
Closing as completed since I have not heard back from the user in ~2 weeks. If you're still having issues @saltyred, let me know.
